module.exports = {
  plugins: [
    'cleanupAttrs',
    'removeDoctype',
    'removeComments',
    'removeUselessDefs',
    'removeEmptyAttrs',
    'removeEmptyContainers',
    'removeMetadata',
    'removeTitle',
    'removeDesc',
    'mergePaths',
    'convertShapeToPath',
    'collapseGroups',
    'cleanupNumericValues',
    'removeUnusedNS',
    'removeNonInheritableGroupAttrs',
    'convertPathData',
    'convertColors',
  ],
};
